//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC497_Project_JagQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccounts_Terms
    {
        public int AccountFK { get; set; }
        public int TermFK { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblTerm tblTerm { get; set; }
    }
}
