//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC497_Project_JagQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public tblAccount()
        {
            this.tblAccounts_Terms = new HashSet<tblAccounts_Terms>();
            this.tblAccounts_Courses = new HashSet<tblAccounts_Courses>();
        }
    
        public int AccountID { get; set; }
        public string JagNumber { get; set; }
        public string bullshit { get; set; }
        public byte[] PasswordHash { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> AccountType { get; set; }
    
        public virtual ICollection<tblAccounts_Terms> tblAccounts_Terms { get; set; }
        public virtual ICollection<tblAccounts_Courses> tblAccounts_Courses { get; set; }
    }
}
