//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC497_Project_JagQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourse
    {
        public tblCourse()
        {
            this.tblAccounts_Courses = new HashSet<tblAccounts_Courses>();
            this.tblTerms = new HashSet<tblTerm>();
        }
    
        public int CourseID { get; set; }
        public string CourseDpt { get; set; }
        public Nullable<int> CourseNum { get; set; }
    
        public virtual ICollection<tblAccounts_Courses> tblAccounts_Courses { get; set; }
        public virtual ICollection<tblTerm> tblTerms { get; set; }
    }
}
