//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSC497_Project_JagQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerm
    {
        public tblTerm()
        {
            this.tblAccounts_Terms = new HashSet<tblAccounts_Terms>();
        }
    
        public int TermID { get; set; }
        public string Term { get; set; }
        public string Def { get; set; }
        public Nullable<int> CourseIDFK { get; set; }
        public Nullable<int> Chapter { get; set; }
    
        public virtual ICollection<tblAccounts_Terms> tblAccounts_Terms { get; set; }
        public virtual tblCourse tblCourse { get; set; }
    }
}
